server:
  port: 8888
spring:
  profiles:
    active: dev
  application:
    name: fund-core
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.wu.fund.entity

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000
hystrix:
  propagate:
    request-attribute:
      enabled: true
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
logging:
  config: classpath:logback-boot.xml
#  metrics:
#    enabled: true
#  config:
#    stream:
#       maxConcurrentConnections: 50
#
#management:
#  port: 9000
#
#turbine:
#   clusters: default
#   location: turbine
