server:
  port: 8888
spring:
  profiles:
    active: dev
  application:
    name: fund-core
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.wu.fund.entity


